### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by perdolka** [Lusito/web-ext-translator#3]
**web-ext-translator** causes an error if the files messages.json contains an "**\u200b**"

For example: https://github.com/piroor/treestyletab/tree/master/webextensions/_locales

<a href="http://piccy.info/view3/12414698/3f76ff6d7cdbc3dfc7e43949c922a816/" target="_blank"><img src="http://i.piccy.info/i9/2cf5b2b31f569db31331a7670ef1518a/1529015259/9303/1246306/sshot_185.png" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-06-14-22-27/i9-12414698/309x355-r" target="_blank"><img src="http://i.piccy.info/a3/2018-06-14-22-27/i9-12414698/309x355-r/i.gif" alt="" border="0" /></a>

**Comment by Lusito** [comment]
Thanks for the report.. I will look into this.

**Comment by Lusito** [comment]
@perdolka could you elaborate as to why you need the value to be a zero-width whitespace?
The new Editor does handle it, but it looks like the textfield is empty, as you can't see a zero-width whitespace. That won't be very useful for translators.

**Comment by Lusito** [comment]
I've made it so that \u won't be replaced by the unicode in the editor, so the translators will see \u200b in the textarea.

In case you want to try the next version, here's a preview:
- http://lusito.info/wet/
- You can load it with your project like this:  
http://lusito.info/wet/?gh=https://github.com/piroor/treestyletab/
- If you enhance your messages.json, you can add groups to make it look like this:  
http://lusito.info/wet/?gh=https://github.com/lusito/forget-me-not/tree/feature/wet

**Comment by Lusito** [comment]
I'm gonna close this as solved
