### ISSUE TITLE
Import from any git repo, not only GitHub

### ISSUE THREAD

**Issue by rugk** [Lusito/web-ext-translator#6]
You know, there is GitLab, BitBucket, Gitea etc., etc.

And as you already allow inserting the URL, you can just import from anywhere.

**Comment by Lusito** [comment]
Thanks for the feedback.

It's not that easy though.. I'm not cloning the git repository. I'm doing everything in the browser.

I can do that with github, because it has an open REST API, which I can use to list all files in the repo and then download the files of interest. I have not looked into other git services, but as long as they supply a REST API or similar, it should be possible.

I will take a look at this.

**Comment by Lusito** [comment]
I've just taken a short look into the 3 provides git hosters and I was able to find an API for GitLab and one for BitBucket, which should be able to support this. I haven't been able to find anything for Gitea though.

**Comment by Lusito** [comment]
I have refactored the code, so that it should be easy to create a provider for gitlab or bitbucket.

After a bit more googling, I was only able to find one single web-extension on Gitlab:
https://gitlab.com/TytoRobotics/RCbenchmarkGUI

And this extension only has a single locale. Bitbucket has no Web-Extension projects at all.
So for now, I'll leave it as it is until someone actually asks for this, because writing and maintaining an importer without proper example extensions is too much work for no benefit.

You are of course welcome to create a pull request yourself.

**Comment by rugk** [comment]
Well… if you just need an example, I could import/mirror my add-on code to/on GitLab.

But I understand your reasons and think this issue can indeed be closed for now. (considering refactoring also fixed that)
