### ISSUE TITLE
Importing my Offline QR Code generator does not work

### ISSUE THREAD

**Issue by rugk** [Lusito/web-ext-translator#8]
STR:
1. Import via GitHub URL: https://github.com/rugk/offline-qr-code

It loads very long and…
Does not work.

Firebox 61

**Comment by Lusito** [comment]
I've just checked and it seems this is due to your messages.json having comments (sorry, I haven't gotten to the part yet where I print parsing error messages to the user).

JSON itself doesn't actually support comments, so I didn't think of implementing this. I've seen your post about comments in web-extension JSON, I will take a look at this.

**Comment by rugk** [comment]
So technically, this is a dupe of https://github.com/Lusito/web-ext-translator/issues/10.

**Comment by Lusito** [comment]
yes, at least partially.. parser errors should still be shown so that the user knows whats going on. That's why I keep this ticket open for now.

**Comment by Lusito** [comment]
The bug is solved.. I'll still leave this issue open, since I haven't yet gotten to show an error message to the user.

**Comment by Lusito** [comment]
I've added code to show an error dialog with some information about the problem. Will be released with the next version.
