### ISSUE TITLE
Buttons are very funny

### ISSUE THREAD

**Issue by rugk** [Lusito/web-ext-translator#9]
Firefox 61:

![buttonsfunny](https://user-images.githubusercontent.com/11966684/42589137-51175150-8540-11e8-91be-37f503018564.gif)

**Comment by Lusito** [comment]
Hmm, that is weird, it doesn't look like this for me. Do you maybe have a dark theme or something that might cause this?
I'm guessing that the default colors have been set by a dark theme and that I need to manually set them so that this doesn't happen.

Will investigate and put up a fix soon. Thanks for the report.

**Comment by rugk** [comment]
No, I have no add-on that modifies the design of websites.

Could not reproduce this issue on Windows though, so maybe it's specific to Linux/GNOME/Fedora.
